// <auto-generated />
using System;
using CODEFIRST_DHinojosa;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CODEFIRST_DHinojosa.Migrations
{
    [DbContext(typeof(ProductsDBContext))]
    [Migration("20240222145931_onlyProductLines")]
    partial class onlyProductLines
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CODEFIRST_DHinojosa.MODEL.ProductLines", b =>
                {
                    b.Property<string>("ProductLine")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("mediumblob");

                    b.Property<string>("TextDescription")
                        .IsRequired()
                        .HasColumnType("varchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<string>("htmlDescription")
                        .IsRequired()
                        .HasColumnType("mediumtext");

                    b.HasKey("ProductLine");

                    b.ToTable("ProductLines");
                });
#pragma warning restore 612, 618
        }
    }
}
